
    create table tb_car (
       id bigint generated by default as identity,
        aso varchar(255),
        car_year varchar(255),
        color varchar(255),
        document varchar(255),
        plate varchar(255),
        security varchar(255),
        vehicle varchar(255),
        user_id bigint,
        primary key (id)
    );

    create table tb_company (
       id bigint generated by default as identity,
        address varchar(255),
        celphone varchar(255),
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table tb_company_rides (
       company_id bigint not null,
        rides_id bigint not null
    );

    create table tb_fowarding (
       id bigint generated by default as identity,
        accepted boolean,
        date TIMESTAMP WITHOUT TIME ZONE,
        driver_id bigint,
        ride_id bigint,
        primary key (id)
    );

    create table tb_ride (
       id bigint generated by default as identity,
        applicant_email varchar(255),
        applicant_name varchar(255),
        consider_car_rotation boolean,
        contact varchar(255),
        cost_center varchar(255),
        destiny varchar(255),
        destiny_address varchar(255),
        favored varchar(255),
        happening boolean,
        motivation varchar(255),
        observations varchar(255),
        origin varchar(255),
        origin_address varchar(255),
        schedule_date timestamp,
        schedule_time time,
        type_favored varchar(255),
        car_id bigint,
        company_id bigint,
        passenger_id bigint,
        primary key (id)
    );

    create table tb_role (
       id bigint generated by default as identity,
        authority varchar(255),
        primary key (id)
    );

    create table tb_status (
       id bigint generated by default as identity,
        date TIMESTAMP WITHOUT TIME ZONE,
        status varchar(255),
        ride_id bigint,
        primary key (id)
    );

    create table tb_user (
       id bigint generated by default as identity,
        cost_center varchar(255),
        email varchar(255),
        faturation boolean,
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        company_id bigint,
        primary key (id)
    );

    create table tb_user_role (
       user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
    );

    alter table tb_company_rides 
       add constraint UK_n05ac8f0vy36srdj0qpatr51l unique (rides_id);

    alter table tb_user 
       add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);

    alter table tb_car 
       add constraint FKlk94od1gnfixxgupy4bsrlx2 
       foreign key (user_id) 
       references tb_user;

    alter table tb_company_rides 
       add constraint FKgp3wfl996dqg6lurtelqpk5f1 
       foreign key (rides_id) 
       references tb_ride;

    alter table tb_company_rides 
       add constraint FK1ha3gjqmf6flq1gb4c7str15c 
       foreign key (company_id) 
       references tb_company;

    alter table tb_fowarding 
       add constraint FK8v3q2ryq1tapqvfo3srypuwm4 
       foreign key (driver_id) 
       references tb_user;

    alter table tb_fowarding 
       add constraint FK43q0wrvlka6ni8eua0k7ubmi1 
       foreign key (ride_id) 
       references tb_ride;

    alter table tb_ride 
       add constraint FK1ftqx8ftsnnj4sba9oi1cviwb 
       foreign key (car_id) 
       references tb_car;

    alter table tb_ride 
       add constraint FKltytmj3hnt3cwj5nkl8cg0dtp 
       foreign key (company_id) 
       references tb_company;

    alter table tb_ride 
       add constraint FKeisoifl8drwtchy6tj7q2utpj 
       foreign key (passenger_id) 
       references tb_user;

    alter table tb_status 
       add constraint FKipxqhs05um0d8c5he01wd1tcj 
       foreign key (ride_id) 
       references tb_ride;

    alter table tb_user 
       add constraint FKib3edn6o0l2nlr2vlpl48idfs 
       foreign key (company_id) 
       references tb_company;

    alter table tb_user_role 
       add constraint FKea2ootw6b6bb0xt3ptl28bymv 
       foreign key (role_id) 
       references tb_role;

    alter table tb_user_role 
       add constraint FK7vn3h53d0tqdimm8cp45gc0kl 
       foreign key (user_id) 
       references tb_user;
INSERT INTO tb_company ( ADDRESS, CELPHONE, EMAIL, NAME) VALUES ('Rua Masuzo Nana', '11 968495753', 'max@gmail.com', 'Max Papéis');
INSERT INTO tb_company ( ADDRESS, CELPHONE, EMAIL, NAME) VALUES ('Rua dos mafagafos', '11 968495753', 'mafagafos@gmail.com', 'Pardão Industrial');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Alex', 'Brown', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Maria', 'Green', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password, company_id) VALUES ('Bob', 'Red', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 1);
INSERT INTO tb_user (first_name, last_name, email, password, company_id) VALUES ('Robert', 'Langdon', 'robert@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 1);
INSERT INTO tb_user (first_name, last_name, email, password, company_id) VALUES ('Jose', 'Red', 'jose@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 2);
INSERT INTO tb_user (first_name, last_name, email, password, company_id) VALUES ('Manoel', 'Langdon', 'manoel@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', 2);
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('João', 'Silva', 'joao.silva@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Ana', 'Santos', 'ana.santos@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Pedro', 'Ferreira', 'pedro.ferreira@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES  ('Carla', 'Oliveira', 'carla.oliveira@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES  ('Paulo', 'Ribeiro', 'paulo.ribeiro@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES  ('Mariana', 'Almeida', 'mariana.almeida@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES  ('Ricardo', 'Gomes', 'ricardo.gomes@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES   ('Sofia', 'Martins', 'sofia.martins@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Tiago', 'Sousa', 'tiago.sousa@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Inês', 'Rodrigues', 'ines.rodrigues@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Luís', 'Fernandes', 'luis.fernandes@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES   ('Andreia', 'Pereira', 'andreia.pereira@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES   ('Hugo', 'Carvalho', 'hugo.carvalho@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES   ('Beatriz', 'Costa', 'beatriz.costa@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES  ('Miguel', 'Machado', 'miguel.machado@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Catarina', 'Nunes', 'catarina.nunes@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Gustavo', 'Lima', 'gustavo.lima@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('Marta', 'Sousa', 'marta.sousa@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (first_name, last_name, email, password) VALUES ('David', 'Oliveira', 'david.oliveira@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_role (authority) VALUES ('ROLE_DRIVER');
INSERT INTO tb_role (authority) VALUES ('ROLE_COMPANY');
INSERT INTO tb_role (authority) VALUES ('ROLE_PASSENGER');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 3);
INSERT INTO tb_user_role (user_id, role_id) VALUES (4, 4);
INSERT INTO tb_user_role (user_id, role_id) VALUES (5, 4);
INSERT INTO tb_user_role (user_id, role_id) VALUES (6, 3);
INSERT INTO tb_user_role (user_id, role_id) VALUES (7, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES   (8, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (9, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (10, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (11, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (12, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (13, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (14, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (15, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (16, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (17, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (18, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (19, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (20, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (21, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (22, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (23, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES  (24, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (25, 2);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES ('34235', '2017', 'preto', 'rnasp21456hx','345fd34','33223442023','Renault Sandero',7);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES ('98765', '2020', 'azul', 'sdjfoiw456hx', '123ab45', '09876543210', 'Fiat Palio', 8);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES   ('54321', '2015', 'vermelho', 'jgksp98765hx', '678cd90', '01234567890', 'Chevrolet Onix', 9);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES  ('24680', '2018', 'branco', 'pzxcb45678hx', '234ef56', '09876543210', 'Volkswagen Gol', 10);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES   ('13579', '2019', 'prata', 'okljh87654hx', '890gh12', '01234567890', 'Ford Fiesta', 11);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES   ('87654', '2016', 'cinza', 'sdhfj32145hx', '345ij67', '09876543210', 'Honda Civic', 12);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES    ('25846', '2021', 'verde', 'bgkiu54231hx', '678kl90', '01234567890', 'Toyota Corolla', 13);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES     ('63948', '2017', 'amarelo', 'zyxwv12345hx', '901mn23', '09876543210', 'Hyundai HB20', 14);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES     ('72638', '2022', 'laranja', 'wertf65432hx', '234op56', '01234567890', 'Nissan Versa', 15);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES     ('91725', '2014', 'roxo', 'qazxs56789hx', '789qr01', '09876543210', 'Renault Logan', 16);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES     ('36482', '2020', 'marrom', 'dfvbn87654hx', '901st23', '01234567890', 'Chevrolet Prisma', 17);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES    ('48752', '2016', 'bege', 'gfdlk32145hx', '234uv56', '09876543210', 'Fiat Uno', 18);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES     ('89264', '2018', 'prata', 'jhytr54321hx', '567wx89', '01234567890', 'Volkswagen Up', 19);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES    ('56324', '2019', 'azul', 'kjuyt87654hx', '901yz01', '09876543210', 'Ford Ka', 20);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES     ('29584', '2015', 'preto', 'rewqo43256hx', '234ab56', '01234567890', 'Honda Fit', 21);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES    ('15672', '2021', 'vermelho', 'nbgfv09876hx', '789cd01', '09876543210', 'Toyota Etios', 22);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES    ('84263', '2017', 'branco', 'hgfdi65432hx', '901ef23', '01234567890', 'Hyundai Creta', 23);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES    ('42735', '2014', 'prata', 'qweas56789hx', '234gh56', '09876543210', 'Nissan Kicks', 24);
INSERT INTO tb_car (ASO, CAR_YEAR, COLOR, DOCUMENT, PLATE, SECURITY, VEHICLE, USER_ID) VALUES    ('37956', '2020', 'cinza', 'uiopk87654hx', '789ij01', '01234567890', 'Renault Duster', 25);
UPDATE tb_user set company_id = 1 where id = 3;
